version: "2"
run:
  go: "1.25"
  tests: true
  timeout: 5m
linters:
  default: none
  enable:
    - asciicheck
    - bodyclose
    - copyloopvar
    - dogsled
    - dupl
    - errcheck
    - exhaustive
    - funlen
    - gochecknoinits
    - gocognit
    - goconst
    - gocritic
    - gocyclo
    - godot
    - goprintffuncname
    - gosec
    - govet
    - ineffassign
    - lll
    - misspell
    - nakedret
    - nestif
    - nolintlint
    - prealloc
    - revive
    - rowserrcheck
    - staticcheck
    - testpackage
    - unconvert
    - unparam
    - unused
    - whitespace
    - wsl_v5
  settings:
    funlen:
      lines: 70
      statements: 50
    gocritic:
      enabled-tags:
        - style
        - experimental
        - performance
        - diagnostic
        - opinionated
    lll:
      line-length: 140
    wsl_v5:
      allow-first-in-block: true
      allow-whole-block: false
      branch-max-lines: 2
  exclusions:
    generated: lax
    presets:
      - comments
      - common-false-positives
      - legacy
      - std-error-handling
    rules:
      - linters:
          - dupl
          - funlen
        path: _test.go
      - linters:
          - gocritic
        path: _test.go
        text: 'hugeParam\: \S+ is heavy \(\d+ bytes\)\; consider passing it by pointer'
    paths:
      - third_party$
      - builtin$
      - examples$
formatters:
  enable:
    - gofmt
    - goimports
  settings:
    goimports:
      local-prefixes:
        - gitlab.services.mts.ru/salsa/mnp-hub/portin-requests
  exclusions:
    generated: lax
    paths:
      - third_party$
      - builtin$
      - examples$
